# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-18 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
